### ISSUE TITLE
A way to shorten dependency lists: wildcards or auto-dependencies

### ISSUE THREAD

**Issue by justinfagnani** [google/wireit#119]
I think a lot of monorepos will have scripts that depend on basically all subpackages. Take lit.dev's `build` script:

```json
  "wireit": {
    "build": {
      "dependencies": [
        "./packages/lit-dev-api:build",
        "./packages/lit-dev-content:build",
        "./packages/lit-dev-server:build",
        "./packages/lit-dev-tests:build",
        "./packages/lit-dev-tools-cjs:build",
        "./packages/lit-dev-tools-esm:build"
      ]
    },
```

This list is prone to getting out of sync as packages are added. That might be caught quickly when the project doesn't build correctly, but the list is still cumbersome.

Lerna and npm solve this by allowing you to run a script by name in any package that has that script. I could see wireit supporting something similar in a few ways:

1. Wildcards:

```json5
  "wireit": {
    "build": {
      "dependencies": [
        "./packages/**/*:build",
      ]
    },
```

2. Wildcard with optional script name
```json5
  "wireit": {
    "build": {
      "dependencies": [
        "./packages/**/*", // Uses "build" automatically
      ]
    },
```

2. Auto-deps based on `"workspaces"` field
This would read the `"workspaces"` field as a single source of truth for the list of all subpackages and run the `build` script in each:

```json5
  "wireit": {
    "build": {
      "dependencies": "auto"
    },
```

This version of the idea would really only be useful on the top-level package. To work in workspaces automatically would require some magic around looking at which dependencies are local to the monorepo and running scripts in them. Maybe that's doable.

Since packages would still need their scripts and dependencies specified, even if auto, it seems like this wouldn't require wireit to topo-sort the packages.

**Comment by luxaritas** [comment]
Another thing Nx does is let you specify default dependencies across all workspaces - ie, in a root configuration file you can note that for the build target in all workspaces, the build target of any dependencies within the package also need to be run

**Comment by rictic** [comment]
The tricky thing about automatic package-level dependencies is that it's not very granular. e.g. maybe `./foo:build` depends on `./bar:build` but `./foo:test` doesn't depend on `./bar:test`, but there's no way to know that without script-level dependencies, which means your caches are invalidated more often and you can run with less parallelism.

**Comment by luxaritas** [comment]
That's where configurability comes in. As I said, what Nx does is let you specify default dependencies across all workspaces for a given script. So you can say the build script in a workspace always depends on the build scripts of its dependencies - that doesn't affect the dependencies of the test scripts. I think it is relatively common for this configuration to work without issues - I'm hard pressed to imagine a situation where a build of a package would not require the dependencies being built. But even if there is some such situation, I'm sure there's other ways to make the configuration more flexible (or at worst, just don't use automatic dependency discovery)

**Comment by calebdwilliams** [comment]
I'm testing wireit for a monorepo at Capital One and will say having automatic dependency checking and script utilities are going to be a huge factor for us in determining our monorepo management tool. 

If wireit could replicate a feature like `lerna run` in some capacity it would be a huge benefit. Workspaces in npm and yarn are close enough but the ability to automatically ignore packages in which that script doesn't exist is crucial for our use case.

I'd be happy with any of the proposals @justinfagnani put forward in the original post, but numbers one and three (really the second "2") make the most sense to me. Big fan of this feature.

**Comment by aomarks** [comment]
> If wireit could replicate a feature like `lerna run` in some capacity it would be a huge benefit. Workspaces in npm and yarn are close enough but the ability to automatically ignore packages in which that script doesn't exist is crucial for our use case.

You can ignore scripts that don't exist using npm workspaces like this:

```sh
npm run build -ws --if-present
```

https://docs.npmjs.com/cli/v7/using-npm/workspaces#ignoring-missing-scripts

See also https://github.com/google/wireit/issues/23, which would provide an explicit way to say "run <script> in all of my workspaces".

Do either or both of those sound like they would work for your use case, @calebdwilliams ?

**Comment by calebdwilliams** [comment]
@aomarks that would work assuming it follows the `--if-present` logic (side note, thanks for pointing that argument out to me, I've been searching for that behavior just haven't found it). 

If we can somehow opt in to caching across all packages inside the workspace that would be ideal. And if we could have a dependencies keyword that opted in to assumed script dependencies based on the package dependencies, that would be 🔥.

**Comment by aomarks** [comment]
> I've moved from `npm-run-all` to `wireit` for paralllel scripts processing and **Glob-like pattern matching for script names** was the first thing I missed out.
> 
> https://github.com/mysticatea/npm-run-all/blob/master/docs/run-p.md#glob-like-pattern-matching-for-script-names

Could you provide an example of where you would like to use this feature? I am curious about whether https://github.com/google/wireit/issues/23 (support `$WORKSPACES` syntax`) would also solve this problem for you -- which would be the case where you want to run the same script name in all of your workspaces.

**Comment by aomarks** [comment]
Closing in favor of https://github.com/google/wireit/issues/23
