### ISSUE TITLE
Add ways to automatically set (or reuse) input files

### ISSUE THREAD

**Issue by justinfagnani** [google/wireit#120]
For tsc we generally already have inputs specified in our tsconfig (though I'm not sure if this is _complete_: tsc may read files outside of the `include` glob without error if they're imported by path). It'd be nice to be able to reuse that. The same might be true of Rollup configs and other tools.

Could there be a way to read input files from tool-specific configs? Maybe this is best for a worker protocol, or may there's a config plug-in system and/or a built-in set of integrations, that know how to read inputs and outputs from common tools.

For tools whose files are specified on the command line, maybe there's a way to specify that once and place it into the command line with substitution.

**Comment by vassudanagunta** [comment]
Prospective new wireit user here. Is there such a standalone tool? I couldn't find any.

**Comment by vassudanagunta** [comment]
Prospective new wireit user here. Is there such a standalone tool? I couldn't find any. With a monorepo and Typescript project references, it's weird to have to code multiple package inputs twice, effectively merging the inputs from all the composite projects.
