### ISSUE TITLE
Consider adding a way to list what a script does

### ISSUE THREAD

**Issue by 43081j** [google/wireit#143]
I often use `npm run` to see a list of commands and glance at what each command actually does.

With wireit, of course all of them will be listed as `wireit` which means we're entirely reliant on the scripts being very well named (which won't always be the case).

It could be useful to have a command somehow which resolves the underlying scripts which will be executed and lists them, kinda like a `npx wireit --list`

**Comment by gunta** [comment]
It would be nice if it can reuse the info from Fig
https://fig.io/docs/guides/autocomplete-for-npm-scripts

**Comment by aomarks** [comment]
I'm hoping to avoid standalone invocations of wireit like `npx wireit --list`. For this use case, personally I use the VSCode extension https://marketplace.visualstudio.com/items?itemName=google.wireit which has support for jump-to-definiton (F2), and also if you hold Control and hover over a script then it shows you the config as well.
