### ISSUE TITLE
Output files are not restored from cache

### ISSUE THREAD

**Issue by mihar-22** [google/wireit#150]
Thanks heaps for open-sourcing this having some fun already, it's awesome. I'm not sure if I'm doing something silly but it seems when I run the `build` command as shown below the files are not restored from cache. Is this expected behaviour because my assumption was it would restore the output files?

![image](https://user-images.githubusercontent.com/14304599/165668463-bb5400c2-26fa-4258-94da-bb9bae1a3353.png)

**Comment by aomarks** [comment]
Hmm, that configuration definitely looks like it should work with caching. Caching to local disk should be enabled if you have both `files` and `output`.

Can you try `ls .wireit/*/cache`? That's where local output caches are saved, so whether there is something there or not would be a clue.

(One side note is that the `packageLocks` currently need to be in _every_ script, but I see you already noticed https://github.com/google/wireit/issues/66).

**Comment by mihar-22** [comment]
I can confirm files are being cached but they're just not being output:

![image](https://user-images.githubusercontent.com/14304599/165675232-e3dd0f88-35c0-445b-82aa-700a047fef85.png)

**Comment by mihar-22** [comment]
To be clear what I mean by restoring is when I manually or through a script delete the output (i.e., `types/` dir), it isn't put back on a subsequent wireit run.

**Comment by aomarks** [comment]
Oh I see.

Wireit does not use the output files of a script to determine whether it should restore from cache or not -- only the input files and some other fields determine that (full list at https://github.com/google/wireit#cache-key) .

So deleting or changing output files of a script independently of the script can confuse things.

If you need to recover from a situation like this, type `rm -rf .wireit/*/state`. This will cause Wireit to either rerun the script or restore them from cache.

**Comment by mihar-22** [comment]
Makes sense, I guess I was coming from Turborepo and I was accustomed to the output files being put back. I guess what I'm asking for is more valuable when remote caching is involved (which I would love to see). Thanks for the swift response.
