### ISSUE TITLE
Node 14.x Support (Vercel)

### ISSUE THREAD

**Issue by mihar-22** [google/wireit#154]
I know it's wild but Vercel is still on `14.x`. Currently deploys fail because of newer syntax such as logical nullish assignment being included in the distribution.

![image](https://user-images.githubusercontent.com/14304599/165752004-958cb48a-4281-4982-8f18-e2b00d7ce137.png)

**Comment by brendankenny** [comment]
FWIW we were just taking a look at wireit for our increasingly hard-to-manage npm script ordering over in [lighthouse](https://github.com/GoogleChrome/lighthouse). Our policy has settled over the years to supporting the Active and _one_ Maintenance LTS (back to Node 14, currently), so this is a blocker for us.

The tsconfig switch to `es2020` would be trivial, but it looks like there are a few Node 15+ features that might be annoying/not worth it to unwind (`AggregateError` and `str.replaceAll` especially). If you did want to expand support, maybe the easiest path would be to not remove Node 16 when it switches to maintenance in October and ease into supporting a maintenance release that way?

**Comment by aomarks** [comment]
Very fair, happy to expand support to cover 14. It is still a supported LTS after all.

You identified all the issues, yeah. All petty trivial. Just need a ponyfill for AggregateError. Let's just write an inline one instead of adding a dep, since it's so simple.

**Comment by aomarks** [comment]
Just published `0.3.0` which supports Node 14.14.0 and above.

**Comment by brendankenny** [comment]
Awesome, thank you @aomarks!
