### ISSUE TITLE
Hovering over npm script should expose command

### ISSUE THREAD

**Issue by e111077** [google/wireit#187]
Given a package.json that looks like this:

```json
{
  "scripts": {
    "build": "wireit",
    "bundle": "wireit"
  },
  "wireit": {
    "build": {
      ...
      "command": "tsc"
    },
    "bundle": {
      ...
      "command": "rollup -c"
    }
  }
}
```

hovering over `scripts.build` should show a tooltip that shows the wireit command associated with it. e.g. `"tsc"`, and hovering over the `scripts.bundle` should show `"rollup -c"`.

If a script does not have a command, then maybe it should not show anything or maybe it should show its dependencies.

Alternatively it should show the wireit config object. But specifically, i just want to be able to scan the "scripts" because the "wireit" object itself is quite expanded because json be like that

**Comment by justinfagnani** [comment]
I'd love general hover-over and jump-to-definition for any wireit reference: cmd-clicking on script.build should ump to the wireit script. cmd-clicking on a dependency should jump to the dependency definition (all the way to the wireit script, skipping the intermediate npm script).

Hovering over a dependency should also display the command the dependency runs and/or a description/doc property added to the wireit section.

**Comment by rictic** [comment]
If you hold down cmd/ctrl and mouse over a dependency or a script in the scripts section it will now show you the configuration for that script

if you then click it will take you to it

**Comment by aomarks** [comment]
> If you hold down cmd/ctrl and mouse over a dependency or a script in the scripts section it will now show you the configuration for that script
> 
> if you then click it will take you to it

Is this issue fixed?
