### ISSUE TITLE
Order script execution by npm dependencies

### ISSUE THREAD

**Issue by JodiWarren** [google/wireit#225]
When working in a monorepo where the packages have varied dependency chains, it is difficult to use WireIt to manage the building of all packages.

The user would effectively need to recreate the internal npm dependencies within the dependencies section of each build command, otherwise a build will result in many missing file dependency file errors.

To illustrate the problem I'm facing, say we had a monorepo with 26 packages, named A-Z. Let's also assume they build in alphabetical order.
- Package A has no internal dependencies
- Package B depends on Packages A and C. 
- Package D depends on Packages A, B, and E. 
- Package F depends on Packages Z, W, and T. 

When the build starts, A builds fine, but the rest fail with errors. B cannot find C, D cannot find B (which failed) or E, and F cannot find any of it's dependencies.

----

The repo I'm currently evaluating with WireIt has approx 115 packages. Once the initial set of built dependencies exists, WireIt is very fast to work with, but that initial build step appears to be a blocker. The only way I can get it working right now is to use a different system to do the initial build.

Apologies if I've misunderstood either the way the project works or the scope of it!

**Comment by aomarks** [comment]
See also https://github.com/google/wireit/issues/119

**Comment by JodiWarren** [comment]
That might well solve it for us and I'll be really interested to see how well it works. So then WireIt would follow the dependency chain for each package that appears within the workspace, build out a dependency tree, and step through, building one by one? The cacheing should make that very fast for subsequent packages with similar dependencies.

I also think the scope for WireIt being different from (say) Lerna is totally reasonable. Lit has a reasonably small amount of packages, with a high degree of difference between them. An explicit and optimisable configuration is probably a great fit there.

**Comment by JodiWarren** [comment]
> Just curious, are you using npm workspaces, or another tool like Lerna for managing your multi-package layout? 

We're currently using a combo of Lerna and Yarn, though we've almost finished moving to PNPM.

> And if you are not using npm workspaces, is npm workspaces something you have looked into/would consider switching to?

We've looked into it, but it's not quite enough on it's own. However, we would strongly consider switching to it if WireIt met all of our other needs. The strong caching means that the local build speed improvement with a primed cache is vast, and we have high hopes for it improving our CI pipeline speed, especially with the Github Actions Cacheing integration.

**Comment by aomarks** [comment]
Closing in favor of tracking at https://github.com/google/wireit/issues/23
