### ISSUE TITLE
package locks in a monorepo

### ISSUE THREAD

**Issue by rictic** [google/wireit#240]
In a monorepo we might have:

./package-lock.json
./child/package-lock.json

I think we want the scripts in child to include both package locks as part of their cache keys. I think we might want to just walk up the dir tree and include _every_ lock file we encounter.

Came up when updating typescript in the base package of the lit monorepo.

**Comment by rictic** [comment]
Hm, I might have misdiagnosed this here

**Comment by aomarks** [comment]
Yeah this is already how it works actually.

https://github.com/google/wireit/blob/main/README.md#:~:text=as%20well%20as%20in%20all%20of%20its%20parent%20directories.

**Comment by aomarks** [comment]
Implementation: https://github.com/google/wireit/blob/3a0082ed5386fb0300167e582a1425505a650581/src/analyzer.ts#L783

**Comment by rictic** [comment]
This was my bad, and not actually a wireit issue!
