### ISSUE TITLE
gitpkg publish runs indefinitely

### ISSUE THREAD

**Issue by appsforartists** [google/wireit#273]
Given this package.json:
```json
  "wireit": {
    "build": {
      "command": "tsc --build --pretty",
      "clean": "if-file-deleted",
      "files": [
        "src/**/*.{ts,tsx}",
        "tsconfig.json",
        "../../tsconfig.common.json"
      ],
      "output": ["dist/**", ".tsbuildinfo"],
      "dependencies": ["../core:build"],
      "packageLocks": ["yarn.lock"]
    },
    "publish": {
      "command": "gitpkg publish",
      "dependencies": ["build"]
    }
  },
```

wireit hangs indefinitely on "Processing…"
```
> yarn run publish
yarn run v1.22.17
$ wireit
✅ [../core:build] Already fresh
✅ [build] Already fresh
🏃 [publish] Running command "gitpkg publish"
gitpkg publish v1.0.0-beta.2
- Processing...

^C
> 💀 [publish] Killed
```

It looks like `gitpkg publish` succeeded.

Maybe if `Processing…` sees the same output for more than 10s, it should echo it so I can see what's happening.

**Comment by 43081j** [comment]
had a little dig, its an infinite loop!

https://github.com/ramasilveyra/gitpkg/blob/884b0fa439b93326fb5df910d4aabc6c706c34ed/src/tasks/Publish/index.js#L38

gitpkg runs the `publish` and `postpublish` scripts as part of its publish command.

in your case, your script which calls gitpkg is called publish, so it ends up calling itself, forever.

maybe we can detect if wireit is called by itself and error if so? (@aomarks may know if thats possible)

**Comment by appsforartists** [comment]
Thanks for investigating!

I'm guessing `"publish": "gitpkg publish"` doesn't cause these issues because it throws an error on the second entrance:

```
  [6/6] 🏇 Running postpublish scripts...
✖ error Command failed with exit code 1: yarn run publish
- Processing...
  [5/6] ⬆️  Uploading package...
✖ error The git tag "…" already exists in "…".
error Command failed with exit code 1.
``` 

I wonder why `wireit` doesn't meet the same fate.

-----

IDK why @ramasilveyra runs `yarn run publish` during `gitpkg publish`.  Perhaps the intent is to push to NPM at the same time as Git, but that seems like a dangerous default (not only because of recursion, but also to keep private packages private).  I haven't seem gitpkg posting to NPM, so that's unlikely to be the reason.

gitpkg doesn't appear to be maintained anymore.  Fixing the problem in the library is a better fix than adding a `recursion: false` option to wireit.  Perhaps I should post a fork of gitpkg with that line commented out.

**Comment by 43081j** [comment]
I doubt it'll get as far as calling gitpkg a second time. I imagine the second time it calls wireit is when it hangs, before it gets around to spawning the inner process (gitpkg).

Maybe to do with the file locking wireit does, or something like that.

**Comment by ramasilveyra** [comment]
Fixed with https://github.com/ramasilveyra/gitpkg/commit/439f75e94f8685f50587f8937036ad05fdae02fe and released in [v1.0.0-beta.3](https://github.com/ramasilveyra/gitpkg/blob/master/CHANGELOG.md#100-beta3-2022-06-07)

**Comment by appsforartists** [comment]
@ramasilveyra Thank you!!!

**Comment by aomarks** [comment]
Seems like this is resolved.
