### ISSUE TITLE
Problems when switching branches

### ISSUE THREAD

**Issue by sorvell** [google/wireit#280]
I generally have problems with wireit when switching between github branches. If a file that the `.wireit` cache expects to exist on disk is deleted (but the `.wireit` cache is not, and it's typically in `.gitignore`), then builds will fail due to `wireit` thinking the build is fresh when the build output is not there. 

It would be great if this were either somehow handled automatically or there was an easy way to address the issue (e.g. better than having to nuke all the `.wireit` files).

**Comment by aomarks** [comment]
https://github.com/google/wireit/issues/292 Should resolve this issue, so will track there.

**Comment by aomarks** [comment]
Wireit 0.6.1 was just released which includes output file verification, which should resolve this issue.
