### ISSUE TITLE
Build fails in Node 14 workflow

### ISSUE THREAD

**Issue by augustjk** [google/wireit#294]
Some node modules are not installed when running `npm ci` in node 14 which causes errors during the typescript build. Specifically `vscode-languageserver`, `vscode-languageserver-textdocument`, and `vscode-languageclient` are needed for the build to be successful.

See https://github.com/google/wireit/runs/6838811493?check_suite_focus=true

This is probably due to npm v6 not supporting workspaces and those dependencies are only listed in `vscode-extension/package.json`.

Potential solutions:
1. Reorganize the files so that `language-server.ts` and `ide.ts` and related tests could be part of the `vscode-extension` package (whose tests are not run in node 14)
2. Split them into a separate package like `language-server`
3. Configure the root project to have separate typescript builds so the `test:headless` can depend on that and run.

**Comment by rictic** [comment]
I think we could just make them dev dependencies in the main wireit package.json
