### ISSUE TITLE
Document releases in this Github repository

### ISSUE THREAD

**Issue by davidsneighbour** [google/wireit#314]
It appears that this repository is the main repo for wireit. Please document releases or at least tag the releases so changes can be referenced between versions via [releases-tab](https://github.com/google/wireit/releases). This is more or less automatic if you "just" tag releases.

**Comment by aomarks** [comment]
They're documented in the CHANGELOG file: https://github.com/google/wireit/blob/main/CHANGELOG.md

**Comment by davidsneighbour** [comment]
Yes, the term "document" was probably wrong. What I meant is running `git tag v0.0.1` and `git tag v0.0.2` so that Github can do its magic and list all changes between these versions. This will also add an entry in the notifications on updates. Having to manually going to CHANGELOG.md works currently.

**Comment by aomarks** [comment]
Sure, I added `vx.x.x` tags to all the release so far, and will do so going forward.
