### ISSUE TITLE
Chained commands in Yarn classic lose reference to "npm_config_argv"

### ISSUE THREAD

**Issue by Westbrook** [google/wireit#545]
If a project wants to follow the pattern that @e111077 has laid out in https://github.com/e111077/11ty-lit/blob/main/package.json#L8 for one non-wireit script to call a wireit script with the `--watch` flag, but uses `yarn` instead of `npm` the following warning is thrown:
```
⚠️ Wireit could not find the script name in the "npm_config_argv" environment variable. Arguments may not be interpreted correctly.
```
While the commands run through initially, the `--watch` instructions are not passed along, and the script will stay open without being rerun on changes as expected.

A cleaner reproduction would be to clone Elliot's project and convert all of the commands to `yarn`, but for a real use case you can checkout https://github.com/adobe/spectrum-web-components/tree/b79cd4ee4d4e08161238a518c549b60725b3448f where the command `yarn docs:start` would expect to enter into a wireit script with the `--watch` flag.

**Comment by aomarks** [comment]
Fixed in v0.9.0
