### ISSUE TITLE
How to handle cross-cutting environment variables

### ISSUE THREAD

**Issue by justinfagnani** [google/wireit#556]
I want to change my builds slightly based on an environment variable, like `ELEVENTY_ENV` which would be valued `"development"` or `"production"`.

I have scripts in my configs that can change behavior based on env variables. I'd like to have two npm scripts to make invoking these easier. One plain script, and one script that sets the env variable first.

For a single script, I could try to do something like:

```json
"scripts": {
  "build:eleventy": {
    "command": "eleventy",
    ...
  },
  "build:eleventy:dev": {
    "command": "ELEVENTY_ENV=development npm run build:eleventy",
  },
}
```

but this becomes tedious when there are other scripts that call these. Each that does would need a `:dev` variant that depends on `:dev` variants itself.

I tried just setting the environment variable before calling `npm`, like `ELEVENTY_ENV=development npm run build`, except that wireit doesn't know that a script depends on an env var, so it won't rerun a script that appears clean, but actually changes output based on the variable.

Is there a better pattern for this?

**Comment by aomarks** [comment]
https://github.com/google/wireit/issues/93 should address this

**Comment by justinfagnani** [comment]
Ah, sorry I missed that!
