### ISSUE TITLE
Don't require dependencies to be in the scripts section

### ISSUE THREAD

**Issue by aomarks** [google/wireit#644]
We're quite strict about every dependency being a real npm script, but sometimes it's nice to have intermediate scripts that are purely defined in the wireit section, even if they can't be invoked directly. This should be allowed.

**Comment by filimon-danopoulos-stratsys** [comment]
This might be a bit backwards in relation to this issue but I believe it is related. 

Assuming I can have "pure" wireit scripts I would like the ability to run the same scripts too but without having to expose them in `scripts`. That way my `package.json` scripts section can be kept very high level, `build`, `lint`, `test` etc without having to care about specifics and dependencies between scripts. 

```json
{ 
  "scripts": {
    "build": "yarn wireit:build",
  },
  "wireit": {
    "wireit:build": {
      "command": "esbuild src/index.ts",
      "clean": "if-file-deleted",
      "files": [
        "./src/**/*"
      ],
      "output": [
        "./dist/**"
      ],
      "dependencies": [
        {
          "script": "wireit:tsc",
          "cascade": false
        }
      ]
    },
    "wireit:tsc": {
      "command": "tsc --project tsconfig.json",
      "clean": true,
      "files": [
        "./src/**/*",
        "tsconfig.json"
      ],
      "output": [
        "./typings/**/*"
      ]
    }
  },
}
```

However when need I would like to tap in to the wireit scripts too, `wireit run wireit:tsc`. In my actual setup I run `lessc`, `esbuild`, `tsc`, and `webpack` as part of the build.
