### ISSUE TITLE
spawn child processes in the same shell

### ISSUE THREAD

**Issue by mshanemc** [google/wireit#648]
I don't run windows, but we do for CI (github actions).

When wireit dependencies run, `shell:true` happens [here](https://github.com/google/wireit/blob/1354ffef5c6ee88371276df6011566e2f0b73dde/src/script-child-process.ts#L94) (see comment in the code)

Our situation: we have some npm scripts that call `./foo`
Our GHA use powershell by default, so these work fine without wireit
Using wireit, they run with cmd.exe (because shell:true => env.comspec => cmd.exe)
cmd.exe can't handle `./`

why not use the same shell that the outer invocation (parent) used?
![Screenshot 2023-01-19 at 10 43 47 AM](https://user-images.githubusercontent.com/4261788/213505216-acbc3f4f-7bbf-486d-83c3-8f53961276f6.png)

**Comment by aomarks** [comment]
We try to replicate the behavior of standard npm scripts, which is to use `/bin/sh` on POSIX and `cmd.exe` on Windows by default (and this just so happens to be the same behavior as node's `shell:true`, so we just use that).

It is true that we don't currently respect the `script-shell` configuration, though, which we should do (https://docs.npmjs.com/cli/v9/using-npm/config#script-shell). Are you using this option, or does yarn behave in a different way?

Detecting the parent shell is a quite good idea, since that would allow us to be agnostic about the shell, and just match the behavior of whichever entrypoint runner was used. I guess we can look up the process tree with `ps` and its equivalent on windows to find the command used for the parent process...

**Comment by mshanemc** [comment]
yarn will follow `script-shell`.

**Comment by aomarks** [comment]
> yarn will follow `script-shell`.

Cool! Are you setting `script-shell` in this situation? Curious if following a `script-shell` flag would solve your problem here, or if there is some other way you are setting the shell?

**Comment by mshanemc** [comment]
I tried setting that but it didn't help.  Sounds like changes to wireit might be the only way to make this work.
 
The bonus there would be that users on windows machines wouldn't have to do anything special (config) to use it--it would use whatever shell they were using at the moment.

**Comment by aomarks** [comment]
I guess I'm trying to understand how you are achieving or would achieve what you want using a vanilla npm/yarn script? My understanding is that you will get `cmd.exe` unless you set `--script-shell` to something else.

**Comment by mshanemc** [comment]
> My understanding is that you will get cmd.exe unless you set --script-shell to something else.

I think that may be the source of confusion.

```json
"scripts": {
  "foo": "./bin/dev go"
}
```

`yarn foo` runs `./bin/dev go` in whatever shell I ran `yarn foo` from.  

Imagine you're a windows user, or running a CI job on windows.  You've chosen powershell (`./` depends on it).  The vanilla script runs in Powershell because that's where it's run from.

When `foo` is used as a wireit dependency of another wireit command, because of the `shell:true` it's going to run `yarn foo` using cmd.exe which will fail (on a windows machine locally or in CI).

**Comment by aomarks** [comment]
> `yarn foo` runs `./bin/dev go` in whatever shell I ran `yarn foo` from.

Looking at the source code, it seems like yarn takes the `custom-shell`, or passes `shell:true`: https://github.com/yarnpkg/yarn/blob/158d96dce95313d9a00218302631cd263877d164/src/util/execute-lifecycle-script.js#L281

That should pretty much match our behavior, except that we don't currently check `custom-shell`.

I don't seem to be seeing any code where it tries to figure out what the parent shell was and use that.

This is for yarn 1.x though, yarn 2.x or 3.x might be different. Which version are you using?

**Comment by mshanemc** [comment]
after looking at yarn's code, I think I agree with you.  I can't square what the code says vs. what happens in GHA, so maybe GHA is doing some things (which code isn't open for) that cause it to use pwsh extensively.

Then wireit's code is maybe finding a way around those settings and managing to run `cmd.exe` where GHA wouldn't.  

I gave up on trying to figure out why, and just rewrote my commands to be usable from `cmd.exe`.
