### ISSUE TITLE
Wireit give me error 

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [google/wireit#678]
![image](https://user-images.githubusercontent.com/45184918/218232549-b8f151ba-2c51-4178-bf9e-cd8cc2ffae22.png)

`"scripts": {
    "dev": "wireit",
    "start": "wireit",
    "build": "wireit",
    "preview": "wireit",
    "astro": "wireit"
  }`

`"wireit": {
    "astro": {
      "command": " astro",
      "packageLocks": [
        "pnpm-lock.yaml"
      ]
    },
    "dev": {
      "command": "dev",
      "service": true,
      "files": [
        "./*{.ts,.json,.cjs}",
        "/package.json"
      ],
      "dependencies": [
        "astro"
      ],
      "env": {}
    }
  }`

**Comment by rictic** [comment]
Unclear bug
