### ISSUE TITLE
Question: could you clarify "dependency" behaviour

### ISSUE THREAD

**Issue by samueljseay** [google/wireit#821]
In the README docs, it talks about scripts not running in parallel unless they can safely do so based on the "dependency graph". Could you clarify is this "dependency graph" formulated from the "dependencies" property of a wireit script, or the npm "dependencies" or both?

The reason I ask is that I have tried migrating a pnpm based monorepo across to wireit from Turborepo and ran into some issues where I expected the npm depdenencies to influence order of scripts running. I have a WIP PR here if you're interested: https://github.com/woocommerce/woocommerce/pull/39504

Basically we have a set of packages under `packages/js`, I want to build them all from the top level, but if a package has a dependency on another monorepo package, that package will need to be built first to get TS types etc built.

I have this kind of index build at top level package json:

```
"build": {
			"dependencies": [
				"./packages/js/ai:build",
				"./packages/js/api:build",
				"./packages/js/components:build",
				"./packages/js/csv-export:build",
				"./packages/js/currency:build",
				"./packages/js/customer-effort-score:build",
				"./packages/js/data:build",
				"./packages/js/date:build",
				"./packages/js/e2e-core-tests:build",
				"./packages/js/experimental:build",
				"./packages/js/explat:build",
				"./packages/js/navigation:build",
				"./packages/js/notices:build",
				"./packages/js/number:build",
				"./packages/js/onboarding:build",
				"./packages/js/product-editor:build",
				"./packages/js/tracks:build"
			]
		}
```

This fails on a clean build right now because for example `/packages/js/components` has a dependency on `/packages/js/date:build` and its not being built first before components is built.

Thanks for any clarifying info you can give. 🙇🏻

**Comment by rictic** [comment]
Having a top level `build` script that depends on the `build` scripts of all of the child packages is using wireit as designed, this should work, assuming that the build scripts in the child packages all express their own dependencies. A wireit script can depend on a vanilla npm script, but vanilla scripts are assumed to have no dependencies and to be uncacheable.

One way that you could see this behavior is if your `build` scripts in the child packages have dependencies among one another without expressing them to `wireit`. `wireit` never infers dependencies between scripts, it only knows what you tell it. So if `components:build` doesn't have `"dependencies": ["../date:build"],` then wireit will run both in parallel.

More formally:

Given two scripts, A and B, when A depends on B then B must be fresh before A runs. That means that either B must run before A can, or if it has both `files` and `output` specified then its output must be restored from cache before A can run.

So if `./packages/js/components:build` is a wireit script with a dependency on `./packages/js/date:build` then the expected wireit behavior is that `date:build` will either run or be restored from cache before `components:build` runs.

**Comment by samueljseay** [comment]
I see thank you very much for the clarification.

I think what you're saying makes sense its just awkward for the particular way our TS builds are organized having to manually declare all dependencies between packages in the wireit build step as well, as it will break subtly for maintainers when they change dependencies. I *think* ideally I would like the ability for wireit to infer parallelism from cross package dependencies in the monorepo as well, but naively I don't know if that makes sense for wireit! 

Turborepo has [that concept](https://turbo.build/repo/docs/core-concepts/monorepos/task-dependencies#from-dependent-workspaces) with it's `^` which indicates that workspace dependencies should be built before a package is built as a separate concern from "task dependencies". Not at all a complaint, just discussing the background of how wireit is different and potentially a blocker for us.
