### ISSUE TITLE
Option to disable [metrics] printed at the end of the run

### ISSUE THREAD

**Issue by rehanvdm** [google/wireit#830]
Can we please get an option to opt out of getting metrics at the end of each run? 

I actually think it should be opt-in for metrics but for now, just a way to turn it off would be great. 

It is noisy and just clutters the output.

**Comment by joshkraft** [comment]
@aomarks - do you have an opinion on if metrics should be opt-in or opt-out? I'm happy to take on the work of reducing the noise since I am largely responsible for introducing the noise 😁

**Comment by rictic** [comment]
This is implemented as of 0.12.0 by setting the `WIREIT_LOGGER` environment variable. Docs: https://github.com/google/wireit#environment-variable-reference

`simple` is the classic wireit output without the metrics summary, and `quiet` is a new logger that will soon be the default.
