### ISSUE TITLE
Running wireit command from outside local folder fails to find dependencies

### ISSUE THREAD

**Issue by thekevinscott** [google/wireit#912]
I have a tree structure like so:

```
- package.json
- packages/
  - foo/
    - package.json
  - bar/
    - package.json
```

My root `package.json` has something like this:

```
{
  "wireit": {
    "build": "pnpm --filter foo build"
  },
}
```

Foo's `package.json` is something like this:

```
{
  "wireit": {
    "build": "pnpm --filter foo build",
    "dependencies": [
      "../foo:build"
    ],
  },
}
```

Running `pnpm` build from the `foo` folder works, but running `pnpm build` from the root folder fails with `package.json file missing:`.

Changing the root package.json to be:

```
    "build": "cd packages/foo && pnpm build"
```

works.

Is there some option for, say, `rootDir`, or some other way to indicate to `wireit` the relative directory it should be calling dependencies from?

**Comment by deebloo** [comment]
im not very familiar with pnpm but why not just just specify `packages/foo:build` as a dependency of the root build command?

**Comment by thekevinscott** [comment]
[`pnpm --filter` is doing some heavy lifting](https://pnpm.io/filtering); it lets you glob like:

```
pnpm --filter "@foo/*" build
```

That'll run `build` in every package that starts with `@foo/`; in a monorepo with lots of packages that's a nice alternative to manually specifying each one.

I don't think there's a way to reproduce behavior like that via a dependency?

**Comment by deebloo** [comment]
If you run 'pnpm --filter foo build' directly from the root does it work?

**Comment by thekevinscott** [comment]
You know, I tried to create a repo from scratch to demonstrate the issue, and can't seem to reproduce this; and my original circumstance is now lost to the sands of time.

I'm happy to close, and if it comes up again I'll make sure to post with an actual repo reproduction this time! :D
